version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_LOG_TO_STDOUT=1
    volumes:
      - rails_storage:/rails/storage
      - rails_db:/rails/db
      - rails_log:/rails/log
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rails_storage:
    driver: local
  rails_db:
    driver: local
  rails_log:
    driver: local

networks:
  app_network:
    driver: bridge
